# Assignment 1

Utilize the designated cells within this notebook to complete the exercises. As for the Python exercises:
- Refrain from altering the provided code; simply fill in the missing portions as indicated.
- Do not use any additional libraries beyond those already included in the code.
- Make sure that the output of all code cells is visible in your submitted notebook. **The evaluator will NOT execute your code before grading your submission.**
- Along with the .ipynb file, you **must** also submitted a PDF version of your work for evaluation.
   
Please identify the authors of this assignment in the cell below.

*AUTHOR NAMES AND STUDENT NUMBERS HERE*

MAGNUS JOHANSEN 202602956

In [ ]:
# Install necessary libraries
%pip install numpy pandas matplotlib

## 1. Probability and Statistics

For this question, you will work with a dataset designed to model **cardiac event risk assessment** based on key physiological markers. 

Cardiovascular risk stratification often relies on non-invasive and minimally invasive clinical measurements. You are provided with measurements collected from a patient cohort, categorized into five continuous physiological variables:


- `systolic_bp_mmHg`: Systolic blood pressure (in mmHg).
- `resting_hr_bpm`: Resting heart rate (in beats per minute).
- `troponin_level_ng_mL`: Serum cardiac troponin concentration (in ng/mL), a key biomarker of cardiac distress/injury.
- `arterial_stiffness_index`: Non-invasive assessment of vascular stiffness and compliance.
- `ox_saturation_pct`: Peripheral arterial oxygen saturation (SpO2, expressed as a percentage).

Target Variable:

- `cardiac_risk`: A binary classification label indicating whether the patient is categorized as Low_Risk or High_Risk. In this case, 0 represents Low_Risk while 1 represents High_Risk.

In [1]:
import pandas as pd 
train_df = pd.read_csv('cardiac_risk_train.csv')
test_df = pd.read_csv('cardiac_risk_test.csv')

train_df.head()

,systolic_bp_mmHg,resting_hr_bpm,troponin_level_ng_mL,arterial_stiffness_index,ox_saturation_pct,cardiac_risk
0,127.1,81.7,0.130,6.18,95.4,High_Risk
1,131.3,64.2,0.161,6.24,95.7,Low_Risk
2,127.2,68.8,0.120,6.79,95.2,High_Risk
3,121.7,69.7,0.101,5.26,96.3,Low_Risk
4,123.1,100.6,0.111,5.73,91.0,High_Risk

1.1 Given that the probability $P(\mathrm{cardiac\_risk}=High\_Risk)=p_{high}$, what is the probability of having exactly $k_{high}$ subjects with high cardiac risk in a population of $N$ individuals?

*YOUR ANSWER HERE*

1.2 With the result obtained in the previous item, apply the MLE method to obtain an equation to estimate the value $p_{high}$.

*YOUR ANSWER HERE*

1.3 Now estimate the values $p_{high}$ and $p_{low}$ for the given training dataset.

In [ ]:
# YOUR CODE GOES HERE

print("p_high: ")
print("p_low: ")

1.4 When observing the features in the dataset, we notice that they are on different scales, for instance `systolic_bp_mmHg` has a mean value of 129.088, while `troponin_level_ng_mL` has a mean of 0.239. Write the code to standardize both the train and test sets. 

*Hint: Be careful to not leak information from the test set!!*

In [ ]:
import numpy as np
print("Mean value for Systolic blood pressure:", np.mean(train_df['systolic_bp_mmHg']))
print("Mean value for Serum cardiac troponin concentration", np.mean(train_df['troponin_level_ng_mL']))

# YOUR CODE GOES HERE

print("Standardized dataset: ")

Mean value for Systolic blood pressure: 129.08875
Mean value for Serum cardiac troponin concentration 0.23999464285714284

*YOUR ANSWER HERE*

1.5 Assuming that the likelihood probability densities follow Gaussian distributions, use MLE to estimate the needed parameters for each class.

In [ ]:
# YOUR CODE GOES HERE

print("Mean vector for class 'High_Risk': ")
print("Mean vector for class 'Low_Risk': ")

print("Covariance matrix for class 'High_Risk': ")
print("Covariance matrix for class 'Low_Risk': ")

1.6 For the previous question, was it necessary that the dataset was standardized? Justify your answer.

*YOUR ANSWER HERE*

1.7 Using the estimated values in the previous questions, evaluate the performance of the proposed model in the test set using the accuracy metric.

In [ ]:
# YOUR CODE GOES HERE

print("Accuracy in the test set: ")

## 2. Linear regression

In this question, you will work with a real-world dataset designed to model **disease progression in diabetes patients** using quantitative baseline physiological measurements.

Predicting disease progression allows clinicians to tailor interventions early. The dataset consists of physiological and diagnostic measurements collected from a patient cohort at baseline, along with a quantitative measure of disease progression recorded one year later.

You are provided with five key baseline features:
- `age`: Age of the patient (in years).
- `bmi`: Body mass index (kg/m2), representing relative body weight.
- `bp`: Average blood pressure (in mmHg).
- `ldl_cholesterol`: Low-density lipoproteins (mg/dL), labeled as ldl ("bad" cholesterol).
- `hdl_cholesterol`: High-density lipoproteins (mg/dL), labeled as hdl ("good" cholesterol).

Target Variable

- `target`: A continuous quantitative measure of disease progression recorded one year after baseline measurements were taken. Higher values indicate more advanced disease progression.

Your task will be to load the dataset (diabetes_regression_train.csv and diabetes_regression_test.csv), inspect the relationships between baseline features and disease progression, build linear regression models, and evaluate their predictive accuracy.

In [12]:
train_df = pd.read_csv('diabetes_regression_train.csv')
test_df = pd.read_csv('diabetes_regression_test.csv')

train_df.head()

    age   bmi     bp  ldl_cholesterol  hdl_cholesterol  target
0  68.0  27.5  111.0            147.0             39.0   144.0
1  46.0  24.7   85.0            123.2             30.0   150.0
2  50.0  31.0  123.0            105.0             48.0   280.0
3  41.0  23.1   86.0             78.0             58.0   125.0
4  42.0  20.3   71.0             81.2             66.0    59.0

2.1 As in the previous question, you should now standardize your dataset. In this case, it is also important to standardize the target variable, why?

In [ ]:
# YOUR CODE HERE
# 
print("Standardized dataset:")

*YOUR ANSWER HERE*

2.2 Assuming the target variable can be described as a linear combination as the features, i.e., $$\hat{y} = \theta_0 + age\times\theta_1 + bmi\times\theta_2 + bp\times\theta_3 + ldl \times \theta_4 + hdl \times \theta_5$$

obtain the solution vector $\hat{\theta}$ that correspond to the parameters that minimize the mean squared error between your estimations $\hat{Y}$ and the ground truth observations $Y$. Evaluate the mean squared error achieved by the proposed model.

In [ ]:
# YOUR CODE HERE 

print("Linear regression (non-regularized)")
print("  theta_hat:", theta_hat)

print("Mean squared error: ")

2.3 In an attempt to improve the model's performance, we decide to use a add a new variable to the problem, *total_cholesterol*, which is defined as:

$$\mathrm{total\_cholesterol} = \mathrm{ldl\_cholesterol} +\mathrm{hdl\_cholesterol}$$

Will the performance of the previous model be improved by adding this new variable? If needed, describe the biological reason of why including this variable may or may not be beneficial, as long as simulations and metrics that support your answer.

*YOUR ANSWER HERE*

In [13]:
# YOUR CODE HERE (if needed)

2.4 Now, obtain the solution vector $\hat{\theta}$ using Ridge regression. You should **include** the *total_cholesterol* variable. Experiment with the regularization term $\lambda=0.1, 1, 10, 100$, and determine which value for $\lambda$ would you choose based on the mean squared error. 

OBS: The term $\theta_0$ must not be regularized, justify why.

In [ ]:
# YOUR CODE HERE 
lambd_values = [0.1, 1, 10, 100]
for lamb in lambd_values:



    print("Linear regression (Ridge regularized)")
    print("  theta_hat:", theta_hat)

    print("Mean squared error:" )

2.5 Repeat the previous question, but now using LASSO regression. In this case, we can use the built in function for LASSO from the sklearn library.

In [ ]:
from sklearn import linear_model

lambd_values = [0.1, 1, 10, 100]
for lamb in lambd_values:
    Lasso = linear_model.Lasso(alpha=lamb)
    # YOUR CODE HERE 
    
    print("Linear regression (regularized)")
    print("  theta_hat:", theta_hat)

    print("Mean squared error:" )

2.6 Compare the results obtained by Linear Regression (without regularization), Ridge Regression, and LASSO Regression. Which one would you choose to deploy as the optimal solution for the problem at hand? Justify your answer.

*YOUR ANSWER HERE*

2.7 Investigate the weights obtained by Ridge Regression and LASSO. Based on the results, which features would you consider the most important to quantify diabetes disease progression? Which ones would you claim as less important? Justify your answer.

*YOUR ANSWER HERE*

2.8 Judge True or False, justify why:
- For us to solve the normal equation: $\hat{\theta} = (X^T X)^{-1} X^T y$, both the rows and columns of $X \in \Re^{n\times d}$, with $n>d$, must be linear independent.
- When $X \in \Re^{d \times d}$ is full rank, the solutions $\bar{\theta} = X^{-1}y$ and $\hat{\theta} = (X^T X)^{-1} X^T y$ will be equal, and the error on the training set will be zero.
- Standardization is only strictly needed for Ridge and LASSO Regression, Linear Regression without regularization does not require the data to be standardized.